eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
  instance:
    hostname: localhost
  
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
      - id: shopping-service
        uri: lb://SHOPPING-SERVICE
        predicates:
        - Path=/shopping/**
      - id: payment-service
        uri: lb://PAYMENT-SERVICE
        predicates:
        - Path=/payment/**
      - id: auth-service
        uri: lb://AUTH-SERVICE
        predicates:
        - Path=/auth/**
          